### ISSUE TITLE
Error to get url get (users)

### ISSUE THREAD

**Issue by Paul75** [piLinux/GoREST#3]
**Describe the bug**
After install and launch no errors but when open http://localhost:3500/api/v1/users/ got errors like in the screen.

**To Reproduce**
1. clone the project
2. configure BDD and like in readme migrate datas
3. launch
4. open browser to http://localhost:3500/api/v1/users
5. see error in console

**Screenshots**
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/457062/101879773-1e077000-3b92-11eb-9fb8-ff73c441543f.png">

**Desktop (please complete the following information):**
 - OS: Mac Os x
 - Browser : Firefox
 - Version [e.g. 22] : 83

Thanks

**Comment by piLinux** [comment]
I created a new Linux virtual instance to produce the error. As you can see, everything went smoothly without any issue.

- In one terminal, the binary is executed
- In terminal 2, a `GET` request is sent using CURL. Since there's no data in the database, it returned an empty JSON array `[ ]`
 
![debug20201211](https://user-images.githubusercontent.com/13842104/101928807-54ff7500-3bd6-11eb-9002-a84e2c7e8e63.PNG)

You will find a log file in the directory from where you run the app. The following is from the log file:
`[GIN] 2020/12/11 - 16:26:37 | 200 |     620.776µs |       127.0.0.1 | GET      /api/v1/users`

Unfortunately, I don't have any macOS to run the same test. But it shouldn't be related to OS if you follow the steps mentioned in the README file.

- Did you run `go build` after cloning the project?
- Can you share the log after sending a `GET` request?

**Comment by Paul75** [comment]
Hello,

I do like you and for me got in log only : 

[GIN] 2020/12/11 - 20:32:46 | 500 |    4.139489ms |             ::1 | GET      /api/v1/users


Thanks

**Comment by Paul75** [comment]
Hello,

Sorry It my fault. I wrong clone project and configure.

Sorry
